line-length = 88
indent-width = 4

[lint]
extend-select = [
    "I",
    "ASYNC",
    "TRIO",
    "S",
    "B",
    "C4",
    "ICN",
    "Q",
    "E",
    "TRY",
    "RUF",
]
ignore = [
    "S101",
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
]
